export default {
  PALETTE_ADD_COLOUR:    'PALETTE_ADD_COLOUR',
  PALETTE_DELETE_COLOUR: 'PALETTE_DELETE_COLOUR',
  PALETTE_FILL:          'PALETTE_FILL',
  PALETTE_SORT:          'PALETTE_SORT',
  PALETTE_SHUFFLE:       'PALETTE_SHUFFLE',
  PALETTE_CLEAR:         'PALETTE_CLEAR'
};
